#ifndef _ALGORITHMS_GUI_GLOBAL_EXPORT_HEADER_
#define _ALGORITHMS_GUI_GLOBAL_EXPORT_HEADER_

#include <QtCore/QtGlobal>

#if defined(BUILDING_ALGORITHMS_GUI_LIBRARY)
#  define ALGORITHMS_GUI_LIB Q_DECL_EXPORT
#else
#  define ALGORITHMS_GUI_LIB Q_DECL_IMPORT
#endif

#endif // _ALGORITHMS_GUI_GLOBAL_EXPORT_HEADER_
